#pragma once

#include <cmath>
#include <complex>
#include <vector>

#include "Types.hpp" // galaxy::Complex (do not modify Types -- only used here)

// ============================================================================
// RUNG 2a: 2D FMM expansions and translation operators (MATH ONLY).
//
// This module is deliberately SEPARATE from any tree/solver code. It implements
// and exposes the operators; the isolated unit tests in fmm_tests.cpp are the
// source of truth. No tree, no passes, no interaction lists, no P2P, no
// ForceSolver wiring -- that is Rung 2b. FMMSolver.hpp stays unassembled.
//
// ----------------------------------------------------------------------------
// CONVENTION (anchored to Kernel.hpp / DirectSolver, the oracle)
//
// Treat each body as a charge q = mass at complex position z. Define the
// complex potential generated by the sources:
//
//       w(z) = sum_j q_j * log(z - z_j)            (complex log)
//
// Then, matching the codebase exactly:
//   * physical scalar potential    phi(z) = G * Re(w(z)) = G * sum_j q_j ln|z-z_j|
//     (so total PE = 0.5 sum_i m_i phi(z_i), consistent with Kernel.hpp).
//   * acceleration (complex vector) a(z)  = G * sum_j q_j (z_j - z)/|z - z_j|^2
//                                         = -G * conj( w'(z) ),
//     because conj(1/(z - z_j)) = (z - z_j)/|z - z_j|^2, and (z_j - z) flips sign.
//     This is EXACTLY DirectSolver's acceleration with eps = 0.
//
// So every operator below works on the analytic w(z); potentials are compared
// via Re(w) and accelerations via -conj(w'). G is a trivial scalar factor and is
// applied at the very end (tests use G = 1).
//
// ----------------------------------------------------------------------------
// EXPANSIONS (Greengard-Rokhlin 2D), each DERIVED from a direct Taylor/series
// expansion in the comments so there are no half-remembered binomial indices.
//
// Multipole about z_c (valid for |z - z_c| > cluster radius):
//       w(z) = Q log(z - z_c) + sum_{k=1}^p a_k (z - z_c)^{-k}
//   with  Q = sum_i q_i,   a_k = -sum_i q_i (z_i - z_c)^k / k.
//   [ log(z - z_i) = log(z-z_c) + log(1 - t),  t = (z_i-z_c)/(z-z_c),
//     log(1-t) = -sum_k t^k/k  =>  a_k = -sum_i q_i (z_i-z_c)^k / k. ]
//
// Local about z_L (valid for |z - z_L| < distance to nearest source):
//       w(z) = sum_{l=0}^p c_l (z - z_L)^l.
// ============================================================================

namespace galaxy {
namespace fmm {

// Binomial coefficients C(n,k) as doubles, precomputed once (n up to 64 covers
// all indices used here, max ~ 2p).
inline double binom(int n, int k) {
    static const int N = 64;
    static const std::vector<std::vector<double>> C = [] {
        std::vector<std::vector<double>> c(N + 1);
        for (int n = 0; n <= N; ++n) {
            c[n].assign(n + 1, 0.0);
            c[n][0] = 1.0;
            for (int k = 1; k <= n; ++k)
                c[n][k] = c[n - 1][k - 1] + (k < n ? c[n - 1][k] : 0.0);
        }
        return c;
    }();
    if (k < 0 || k > n || n > N) return 0.0;
    return C[n][k];
}

// Multipole expansion: Q is the total charge (the log term a_0); a[1..p] are the
// inverse-power coefficients. a[0] is unused.
struct Multipole {
    Complex center{0.0, 0.0};
    int p = 0;
    Complex Q{0.0, 0.0};
    std::vector<Complex> a; // size p+1, indices 1..p valid

    Multipole() = default;
    Multipole(Complex c, int order) : center(c), p(order), a(order + 1, Complex{0, 0}) {}
};

// Local (Taylor) expansion: c[0..p].
struct Local {
    Complex center{0.0, 0.0};
    int p = 0;
    std::vector<Complex> c; // size p+1, indices 0..p

    Local() = default;
    Local(Complex ctr, int order) : center(ctr), p(order), c(order + 1, Complex{0, 0}) {}
};

// ---- P2M: form a multipole about z_c from sources (q_i at z_i) -------------
inline Multipole P2M(Complex center, const std::vector<Complex>& pos,
                     const std::vector<double>& q, int p) {
    Multipole M(center, p);
    for (std::size_t i = 0; i < pos.size(); ++i) {
        M.Q += q[i];
        const Complex d = pos[i] - center; // z_i - z_c
        Complex dk = d;                    // d^k
        for (int k = 1; k <= p; ++k) {
            M.a[k] += -q[i] * dk / static_cast<double>(k);
            dk *= d;
        }
    }
    return M;
}

// ---- Multipole evaluation: w(z) and w'(z) ----------------------------------
inline Complex multipolePotential(const Multipole& M, Complex z) {
    const Complex dz = z - M.center;
    Complex w = M.Q * std::log(dz);
    Complex invk = 1.0 / dz; // (dz)^{-k}, k=1..
    for (int k = 1; k <= M.p; ++k) {
        w += M.a[k] * invk;
        invk /= dz;
    }
    return w;
}

inline Complex multipoleField(const Multipole& M, Complex z) {
    // w'(z) = Q/(z-zc) - sum_k k a_k (z-zc)^{-(k+1)}
    const Complex dz = z - M.center;
    const Complex inv = 1.0 / dz;
    Complex w = M.Q * inv;
    Complex invk1 = inv * inv; // (dz)^{-(k+1)} starting at k=1 -> dz^{-2}
    for (int k = 1; k <= M.p; ++k) {
        w += -static_cast<double>(k) * M.a[k] * invk1;
        invk1 *= inv;
    }
    return w;
}

// ---- M2M: shift a multipole from its center to newCenter -------------------
// Re-expand Q log(z-zc) + sum a_k (z-zc)^{-k} about newCenter. With d = zc - zp:
//   b_l = -Q d^l / l + sum_{k=1}^l a_k d^{l-k} C(l-1, k-1).
inline Multipole M2M(const Multipole& M, Complex newCenter) {
    Multipole R(newCenter, M.p);
    R.Q = M.Q;
    const Complex d = M.center - newCenter;
    std::vector<Complex> dp(M.p + 1);
    dp[0] = Complex{1, 0};
    for (int i = 1; i <= M.p; ++i) dp[i] = dp[i - 1] * d;
    for (int l = 1; l <= M.p; ++l) {
        Complex bl = -M.Q * dp[l] / static_cast<double>(l);
        for (int k = 1; k <= l; ++k)
            bl += M.a[k] * dp[l - k] * binom(l - 1, k - 1);
        R.a[l] = bl;
    }
    return R;
}

// ---- M2L: convert a multipole (about z_c) to a local expansion (about z_L) --
// Derived by Taylor-expanding the multipole's terms about z_L with D = z_L - z_c:
//   log(z - z_c) = log(D + u),  u = z - z_L:
//       contributes a_0 log D to c_0, and -Q(-1)^l/(l D^l) to c_l (l>=1).
//   a_k (z - z_c)^{-k} = a_k (D + u)^{-k}, (1+u/D)^{-k} = sum_l (-1)^l C(k+l-1,l) (u/D)^l:
//       contributes a_k/D^k to c_0, and (-1)^l a_k C(k+l-1, k-1)/D^{k+l} to c_l.
// =>  c_0 = Q log(D) + sum_k a_k / D^k
//     c_l = (-1)^l [ -Q/(l D^l) + sum_k a_k C(k+l-1, k-1) / D^{k+l} ],  l >= 1.
inline Local M2L(const Multipole& M, Complex localCenter) {
    Local R(localCenter, M.p);
    const Complex D = localCenter - M.center;
    const Complex invD = 1.0 / D;
    std::vector<Complex> invDp(2 * M.p + 2); // D^{-i}
    invDp[0] = Complex{1, 0};
    for (std::size_t i = 1; i < invDp.size(); ++i) invDp[i] = invDp[i - 1] * invD;

    Complex c0 = M.Q * std::log(D);
    for (int k = 1; k <= M.p; ++k) c0 += M.a[k] * invDp[k];
    R.c[0] = c0;

    for (int l = 1; l <= M.p; ++l) {
        Complex s = -M.Q * invDp[l] / static_cast<double>(l);
        for (int k = 1; k <= M.p; ++k)
            s += M.a[k] * binom(k + l - 1, k - 1) * invDp[k + l];
        const double sign = (l % 2 == 0) ? 1.0 : -1.0;
        R.c[l] = sign * s;
    }
    return R;
}

// ---- L2L: shift a local expansion from its center to newCenter -------------
// Re-expand sum c_l (z - zL)^l about newCenter. With e = newCenter - zL:
//   d_m = sum_{l=m}^p c_l C(l, m) e^{l-m}.
inline Local L2L(const Local& L, Complex newCenter) {
    Local R(newCenter, L.p);
    const Complex e = newCenter - L.center;
    std::vector<Complex> ep(L.p + 1);
    ep[0] = Complex{1, 0};
    for (int i = 1; i <= L.p; ++i) ep[i] = ep[i - 1] * e;
    for (int m = 0; m <= L.p; ++m) {
        Complex dm{0, 0};
        for (int l = m; l <= L.p; ++l) dm += L.c[l] * binom(l, m) * ep[l - m];
        R.c[m] = dm;
    }
    return R;
}

// ---- Local evaluation: w(z) and w'(z) --------------------------------------
inline Complex localPotential(const Local& L, Complex z) {
    const Complex u = z - L.center;
    Complex up{1, 0}; // u^l
    Complex w{0, 0};
    for (int l = 0; l <= L.p; ++l) {
        w += L.c[l] * up;
        up *= u;
    }
    return w;
}

inline Complex localField(const Local& L, Complex z) {
    // w'(z) = sum_{l>=1} l c_l (z - zL)^{l-1}
    const Complex u = z - L.center;
    Complex up{1, 0}; // u^{l-1}
    Complex w{0, 0};
    for (int l = 1; l <= L.p; ++l) {
        w += static_cast<double>(l) * L.c[l] * up;
        up *= u;
    }
    return w;
}

// ---- Convert the complex field w'(z) to the codebase acceleration ----------
//   a(z) = -G * conj( w'(z) ).  Matches DirectSolver (eps = 0) exactly.
inline Complex fieldToAccel(Complex field, double G = 1.0) {
    return -G * std::conj(field);
}

} // namespace fmm
} // namespace galaxy
